version: '3'

services:
  duo_web:
    build: ./backend/
    ports:
      - "5000:5000"
    volumes:
      - "./src/:/usr/src/"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run.py
      FLASK_ENV: development
    networks: 
      - default
      - shared-network
    command: flask run -h 0.0.0.0
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/usr/db/
    ports:
      - "3306:3306"
networks: 
  shared-network:
    external: true